"""initial_schema

Revision ID: 0e6839a1a121
Revises: 
Create Date: 2026-09-11 05:42:07.579011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6839a1a121'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=True),
    sa.Column('source_name', sa.String(length=500), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('raw_business_name', sa.String(length=500), nullable=True),
    sa.Column('normalized_business_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('normalized_phone', sa.String(length=64), nullable=True),
    sa.Column('normalized_website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('has_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('website_status', sa.Enum('UNKNOWN', 'WEBSITE_FOUND', 'NO_WEBSITE', name='websitestatus', native_enum=False, length=50), nullable=False),
    sa.Column('source_platform', sa.String(length=100), nullable=True),
    sa.Column('qualification_status', sa.String(length=50), nullable=False),
    sa.Column('last_outreach_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_business_name'), ['business_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_canonical_name'), ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_last_contacted_at'), ['last_contacted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_last_outreach_at'), ['last_outreach_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_normalized_business_name'), ['normalized_business_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_normalized_phone'), ['normalized_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_normalized_website'), ['normalized_website'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_qualification_status'), ['qualification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_website_status'), ['website_status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SALES', 'VIEWER', name='userrole', native_enum=False, length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_otp', sa.String(length=32), nullable=True),
    sa.Column('verification_otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_failed_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('is_decision_maker', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('normalized_phone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_normalized_phone'), ['normalized_phone'], unique=False)

    op.create_table('crawled_websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('location_signature', sa.String(length=255), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('branches', sa.JSON(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawled_websites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawled_websites_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawled_websites_domain'), ['domain'], unique=False)
        batch_op.create_index('ix_crawled_websites_domain_loc', ['domain', 'location_signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawled_websites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawled_websites_location_signature'), ['location_signature'], unique=False)

    op.create_table('discovery_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('query', sa.JSON(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('total_discovered', sa.Integer(), nullable=False),
    sa.Column('total_processed', sa.Integer(), nullable=False),
    sa.Column('new_leads', sa.Integer(), nullable=False),
    sa.Column('existing_businesses', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('export_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'RUNNING', 'COMPLETED', 'FAILED', name='exportstatus', native_enum=False, length=32), nullable=False),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('LEAD', 'CONTACTED', 'QUALIFIED', 'PROPOSAL', 'WON', 'LOST', name='pipelinestage', native_enum=False, length=50), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='leadpriority', native_enum=False, length=50), nullable=False),
    sa.Column('signal', sa.Enum('COLD', 'WARM', 'HOT', name='leadsignal', native_enum=False, length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_business_id'), ['business_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_leads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_signal'), ['signal'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_stage'), ['stage'], unique=False)

    op.create_table('prospect_demos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('custom_overrides', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prospect_demos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prospect_demos_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospect_demos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospect_demos_token'), ['token'], unique=True)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_endpoint'), ['endpoint'], unique=True)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('BUSINESS_DISCOVERED', 'LEAD_CREATED', 'WEBSITE_VISITED', 'CALL_INITIATED', 'WHATSAPP_OPENED', 'EMAIL_INITIATED', 'INTERACTION_LOGGED', 'NOTE_ADDED', 'TASK_CREATED', 'TASK_COMPLETED', 'REMINDER_CREATED', 'REMINDER_COMPLETED', 'STATUS_CHANGED', 'PROPOSAL_SENT', name='activitytype', native_enum=False, length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_user_id'), ['user_id'], unique=False)

    op.create_table('business_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('discovery_job_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_business_source_platform_external_id')
    )
    with op.batch_alter_table('business_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_sources_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_business_sources_business_platform', ['business_id', 'platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_sources_discovery_job_id'), ['discovery_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_sources_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_sources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_sources_platform'), ['platform'], unique=False)

    op.create_table('demo_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demo_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('page_path', sa.String(length=255), nullable=True),
    sa.Column('referrer', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demo_id'], ['prospect_demos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demo_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demo_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_demo_events_demo_id'), ['demo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demo_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_demo_events_id'), ['id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_user_id'), ['user_id'], unique=False)

    op.create_table('outreaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('CALL', 'WHATSAPP', 'EMAIL', name='outreachchannel', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'CONNECTED', 'NO_ANSWER', 'BUSY', 'SENT', 'DELIVERED', 'REPLIED', 'BOUNCED', 'FAILED', name='outreachstatus', native_enum=False, length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreaches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreaches_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreaches_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreaches_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreaches_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreaches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreaches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreaches_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus', native_enum=False, length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('outreach_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('CALL_CONVERSATION', 'WHATSAPP_CHAT', 'EMAIL_THREAD', 'MEETING', 'DEMO', name='interactiontype', native_enum=False, length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreaches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_outreach_id'), ['outreach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_user_id'), ['user_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='reminderstatus', native_enum=False, length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_notification_sent_at'), ['notification_sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_task_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_reminders_notification_sent_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_due_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_contact_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_business_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_type'))
        batch_op.drop_index(batch_op.f('ix_interactions_outreach_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_interactions_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_contact_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_business_id'))

    op.drop_table('interactions')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_contact_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_business_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('outreaches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreaches_user_id'))
        batch_op.drop_index(batch_op.f('ix_outreaches_status'))
        batch_op.drop_index(batch_op.f('ix_outreaches_id'))
        batch_op.drop_index(batch_op.f('ix_outreaches_contact_id'))
        batch_op.drop_index(batch_op.f('ix_outreaches_channel'))
        batch_op.drop_index(batch_op.f('ix_outreaches_business_id'))
        batch_op.drop_index(batch_op.f('ix_outreaches_attempted_at'))

    op.drop_table('outreaches')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_notes_id'))
        batch_op.drop_index(batch_op.f('ix_notes_contact_id'))
        batch_op.drop_index(batch_op.f('ix_notes_business_id'))

    op.drop_table('notes')
    with op.batch_alter_table('demo_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demo_events_id'))
        batch_op.drop_index(batch_op.f('ix_demo_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_demo_events_demo_id'))
        batch_op.drop_index(batch_op.f('ix_demo_events_created_at'))

    op.drop_table('demo_events')
    with op.batch_alter_table('business_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_sources_platform'))
        batch_op.drop_index(batch_op.f('ix_business_sources_id'))
        batch_op.drop_index(batch_op.f('ix_business_sources_external_id'))
        batch_op.drop_index(batch_op.f('ix_business_sources_discovery_job_id'))
        batch_op.drop_index('ix_business_sources_business_platform')
        batch_op.drop_index(batch_op.f('ix_business_sources_business_id'))

    op.drop_table('business_sources')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_activities_type'))
        batch_op.drop_index(batch_op.f('ix_activities_id'))
        batch_op.drop_index(batch_op.f('ix_activities_entity_type'))
        batch_op.drop_index(batch_op.f('ix_activities_entity_id'))
        batch_op.drop_index(batch_op.f('ix_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_activities_contact_id'))
        batch_op.drop_index(batch_op.f('ix_activities_business_id'))

    op.drop_table('activities')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_endpoint'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('prospect_demos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospect_demos_token'))
        batch_op.drop_index(batch_op.f('ix_prospect_demos_id'))
        batch_op.drop_index(batch_op.f('ix_prospect_demos_business_id'))

    op.drop_table('prospect_demos')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_stage'))
        batch_op.drop_index(batch_op.f('ix_leads_signal'))
        batch_op.drop_index(batch_op.f('ix_leads_priority'))
        batch_op.drop_index(batch_op.f('ix_leads_owner_id'))
        batch_op.drop_index(batch_op.f('ix_leads_id'))
        batch_op.drop_index(batch_op.f('ix_leads_business_id'))

    op.drop_table('leads')
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_export_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_export_jobs_id'))

    op.drop_table('export_jobs')
    with op.batch_alter_table('discovery_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_discovery_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_discovery_jobs_id'))

    op.drop_table('discovery_jobs')
    with op.batch_alter_table('crawled_websites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawled_websites_location_signature'))
        batch_op.drop_index(batch_op.f('ix_crawled_websites_id'))
        batch_op.drop_index('ix_crawled_websites_domain_loc')
        batch_op.drop_index(batch_op.f('ix_crawled_websites_domain'))
        batch_op.drop_index(batch_op.f('ix_crawled_websites_business_id'))

    op.drop_table('crawled_websites')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_normalized_phone'))
        batch_op.drop_index(batch_op.f('ix_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_business_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_website_status'))
        batch_op.drop_index(batch_op.f('ix_businesses_qualification_status'))
        batch_op.drop_index(batch_op.f('ix_businesses_normalized_website'))
        batch_op.drop_index(batch_op.f('ix_businesses_normalized_phone'))
        batch_op.drop_index(batch_op.f('ix_businesses_normalized_business_name'))
        batch_op.drop_index(batch_op.f('ix_businesses_last_outreach_at'))
        batch_op.drop_index(batch_op.f('ix_businesses_last_contacted_at'))
        batch_op.drop_index(batch_op.f('ix_businesses_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_city'))
        batch_op.drop_index(batch_op.f('ix_businesses_category'))
        batch_op.drop_index(batch_op.f('ix_businesses_canonical_name'))
        batch_op.drop_index(batch_op.f('ix_businesses_business_name'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
